app/app/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

app/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('event/add/', views.event_add, name='event_add'),  # 登録
    path('event/edit/', views.event_edit_prepare, name='event_edit_prepare'),  # 編集
    path('event/kouho/', views.event_kouho_print, name='event_kouho'),  # イベント日時候補
    path('event/notify_event_add_completed/', views.notify_event_add_completed, name='notify_event_add_completed'),  # イベント追加完了
    path('event/fill/', views.schedule_fill, name='schedule_fill'),  # 参加可否記入
    path('', views.index, name='index'),
]

app/home/models.py
from django.core.exceptions import ValidationError
from django.db import models

def only_intger(value):
    if value.isdigit() == False:
        raise ValidationError('暗証番号は4桁の数字を入力して下さい。')


class Event(models.Model):
    """イベント"""
    name = models.CharField('イベント名', max_length=255)
    memo = models.CharField('メモ', max_length=255, blank=True)
    schedule_update_id = models.CharField('スケジュール更新ID', max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'イベント情報'
        verbose_name_plural = verbose_name


class EventKouhoNichiji(models.Model):
    """イベント候補日時"""
    event = models.ForeignKey(Event, verbose_name='イベント', related_name='event_kouho_nichiji_set', on_delete=models.CASCADE)
    kouho_nichiji = models.CharField('候補日時', max_length=255)

    def __str__(self):
        return self.kouho_nichiji

    class Meta:
        verbose_name = 'イベント候補日時情報'
        verbose_name_plural = verbose_name


class Sankasha(models.Model):
    """
    参加者
    ※参加者の情報を保持する
    """
    event = models.ForeignKey(Event, verbose_name='イベント', related_name='sankasha_set', on_delete=models.CASCADE)
    name = models.CharField('参加者名', max_length=255)
    comment = models.CharField('コメント', max_length=1024, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '参加者情報'
        verbose_name_plural = verbose_name


class SankaNichiji(models.Model):
    """
    参加日時
    ※参加者の各日時の参加可否を保持する
    """
    sankasha = models.ForeignKey(Sankasha, verbose_name='参加者', related_name='sankasha_sanka_nichiji_set', on_delete=models.CASCADE)
    event_kouho_nichiji = models.ForeignKey(EventKouhoNichiji, verbose_name='イベント候補日時', related_name='event_kouho_sanka_nichiji_set', on_delete=models.CASCADE)
    sanka_kahi = models.IntegerField('参加可否')

    def __str__(self):
        return self.sanka_kahi

    class Meta:
        verbose_name = '参加日時情報'
        verbose_name_plural = verbose_name

app/home/forms.py
from django import forms
from django.forms import CheckboxInput

from home.models import Event, Sankasha


class EventForm(forms.ModelForm):
    """
    イベントのフォーム
    """

    class Meta:
        model = Event
        fields = ('name', 'memo',)
        error_messages = {
            'name': {
                'required': 'イベント名は必須です!'
            }
        }

    event_datetime_kouho = forms.CharField(
        label='イベント日時候補',
        required=True,
        max_length=255,
        error_messages={'required': 'イベント日時候補は必須です!', }
    )


class EventEditForm(EventForm):
    """
    イベント編集のフォーム
    """
    event_datetime_kouho = forms.CharField(
        label='イベント日時候補',
        required=False,
        max_length=255,
    )

    key = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta(EventForm.Meta):
        fields = ('name', 'memo')

    def __init__(self, *args, **kwargs):
        # エンコ済イベントテーブルID
        key_value = kwargs.pop('key', None)
        # 削除対象候補チェックボックス全量
        event_datetime_dict = kwargs.pop('event_datetime_dict', None)
        # 前画面でのチェック済チェックボックス
        del_event_datetime_kouho_id_list = kwargs.pop('del_event_datetime_kouho_id_list', None)

        super(EventEditForm, self).__init__(*args, **kwargs)

        self.fields['key'].initial = key_value

        for eve_dt_kouho_id, nichiji_str in event_datetime_dict.items():
            # eve_dt_kouho_id: イベント日時候補テーブルID
            # nichiji_str: イベント日時候補文字列（X月Y日Z時等）
            field_name = 'del_eve_dt_kouho_id_' + str(eve_dt_kouho_id)
            attrs = {'value': eve_dt_kouho_id}
            if field_name in del_event_datetime_kouho_id_list:
                attrs['checked'] = 'checked'
            self.fields[field_name] = forms.BooleanField(label=nichiji_str, widget=CheckboxInput(attrs=attrs), required=False)


class EventSankakahiForm(forms.ModelForm):
    """
    イベント参加可否のフォーム
    """

    class Meta:
        model = Sankasha
        fields = ('name', 'comment',)
        error_messages = {
            'name': {
                'required': '名前は必須です!'
            }
        }

    sankasha_id = forms.HiddenInput()

    def add_sankakahi_form(self, name):
        self.fields[name] = forms.ChoiceField(
            required=False,
            initial=0
        )

app/home/views.py
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# ■views.py
# TODO ロギング→デコレータを利用する。
# http://shimada-k.hateblo.jp/entry/2019/12/09/125244
# TODO 例外ハンドラ→これもデコレータを実装する。エラーが発生したらerror.htmlへ遷移させる。
# https://qiita.com/homines22/items/dccae65fa3434641b995
# TODO イベント日時候補テーブルに関する変数名・表記揺れ
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
import json
from urllib.parse import urlencode

from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from home import helpers, constants
from home.forms import EventForm, EventSankakahiForm, EventEditForm
from home.helpers import get_event_datetime_dict, render_with_histories
from home.models import Event, EventKouhoNichiji, SankaNichiji, Sankasha


# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# トップページ遷移関数
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
def index(request):  # 追加
    """イベントの一覧"""
    events = Event.objects.all().order_by('id')
    return render_with_histories(request,
                                 'home/top.html')


# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# イベント追加・編集関数
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
def event_add(request):
    """
    イベントの追加・編集
    """

    # ===================================================
    # パラメータ取得
    # ===================================================
    # ------------------------
    # EventテーブルID
    # ------------------------
    event_id = None
    schedule_update_id = request.POST.get('key')
    # イベント追加画面（新規登録）から来た（True）のか、編集画面から来たのか
    is_event_add = schedule_update_id == None
    if not is_event_add:
        event_id = helpers.decode_from_schedule_update_id(schedule_update_id)

    # ------------------------
    # 削除対象のイベント日時候補ID調査
    # ------------------------
    del_event_datetime_kouho_id_list = {}
    if not is_event_add:
        for key in request.POST:
            if 'del_eve_dt_kouho_id_' in key:
                del_event_datetime_kouho_id_list[key] = request.POST[key]

    # ===================================================
    # Formオブジェクト作成
    # ===================================================
    if is_event_add:
        # イベント追加画面（新規登録）から来たとき
        form = EventForm(request.POST)
    else:
        # イベント編集画面から来たとき
        event = Event.objects.get(pk=event_id)
        event_datetime_dict = get_event_datetime_dict(event)
        # パラメータ3,4は、チェックボックス（表示とチェック状態）を準備するために使う
        form = EventEditForm(
            request.POST,  # 1.
            key=schedule_update_id,  # 2.
            event_datetime_dict=event_datetime_dict,  # 3. 削除対象候補チェックボックス全量
            del_event_datetime_kouho_id_list=del_event_datetime_kouho_id_list  # 4. 前画面でのチェック済チェックボックス
        )

    if form.is_valid():  # フォームのバリデーション
        with transaction.atomic():
            # ===================================================
            # 保存対象モデルデータ作成
            # ===================================================
            event = form.save(commit=False)

            # ===================================================
            # 保存処理 #1
            # ※2つに分けている理由：新規登録の場合、一旦保存しないとPKが採番されないため。
            # ===================================================
            if is_event_add:
                # スケジュール更新ページIDが渡されなかった場合のみ保存する
                event.save()
            else:
                # スケジュール更新ページIDが渡された場合は既存レコードを保存対象とする
                event.id = event_id

            # ===================================================
            # イベント日時候補レコード削除
            # ※編集画面にて削除を選択された日時がある場合の処理
            # ===================================================
            if not is_event_add:
                for del_id in del_event_datetime_kouho_id_list.values():
                    # Deleteクエリが対象数分繰り替えされるが少数であると考えられるのでこれで削除する
                    EventKouhoNichiji.objects.filter(id=del_id).delete()
                    # TODO 下記に変える
                    # EventKouhoNichiji.objects.raw('DELETE FROM xxxx WHERE id IN (%s)', [','.join([del_event_datetime_kouho_id_list])])

            # ===================================================
            # イベント日時候補レコード作成処理
            # 　画面の「イベント日時候補」※に入力された文字列を取得、処理して保存対象データを加工・作成する。
            # 　※改行コード区切り
            # ===================================================
            event_datetime_kouhos = helpers.get_event_datetime_kouhos(form.cleaned_data['event_datetime_kouho'])

            # ===================================================
            # 保存対象データ設定処理
            # ===================================================
            # ------------------------
            # イベント
            # ------------------------
            # スケジュール更新ページID
            schedule_update_id = helpers.create_schedule_update_id(event.id)
            event.schedule_update_id = schedule_update_id

            # ------------------------
            # イベント日時候補
            # ------------------------
            eventKouhoNichijis = []
            for event_datetime_kouho in event_datetime_kouhos:
                if event_datetime_kouho != '':
                    eventKouhoNichijis.append(EventKouhoNichiji(event=event, kouho_nichiji=event_datetime_kouho))

            # ===================================================
            # 保存処理 #2
            # ===================================================
            if len(eventKouhoNichijis) != 0: EventKouhoNichiji.objects.bulk_create(eventKouhoNichijis)
            event.save()

        # ===================================================
        # 次画面遷移
        # ===================================================
        # ------------------------
        # リダイレクト先のパスを取得する
        # ------------------------
        redirect_url = reverse('home:notify_event_add_completed')

        # ------------------------
        # パラメータのdictをurlencodeする
        # ------------------------
        parameters = urlencode({'key': schedule_update_id})

        # ------------------------
        # URLにパラメータを付与して遷移する
        # ------------------------
        url = f'{redirect_url}?{parameters}'
        return redirect(url)

    # ===================================================
    # フォームバリデーションエラー時の次画面遷移
    # ===================================================
    if is_event_add:
        # イベント新規登録画面（TOP画面）へ遷移
        return render_with_histories(request, 'home/top.html', dict(form=form), event_id=event_id)
    else:
        # イベント編集画面へ遷移
        params = dict(form=form)
        return render_with_histories(request, 'home/event_edit.html', params, event_id=event_id)


# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# イベント追加完了ページ遷移関数
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
def notify_event_add_completed(request):
    """イベント追加完了"""
    # ------------------------
    # スケジュール編集URLを取得する
    # ------------------------
    schedule_update_id = request.GET.get('key')
    event_id = helpers.decode_from_schedule_update_id(schedule_update_id)
    parameters = urlencode({'key': schedule_update_id})
    schedule_fill_url = reverse('home:event_kouho')
    schedule_fill_url = "{}://{}{}?{}".format(request.scheme, request.get_host(), schedule_fill_url, parameters)

    return render_with_histories(request,
                                 'home/notify_event_add_completed.html',  # 使用するテンプレート
                                 {'schedule_fill_url': schedule_fill_url},  # テンプレートに渡すデータ
                                 event_id=event_id)


# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
# イベント日時候補表示関数
# ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
def event_kouho_print(request):
    """各個人のスケジュール更新画面表示"""

    # ===================================================
    # パラメータ取得
    # ===================================================
    # ------------------------
    # スケジュール更新ページID
    # ------------------------
    schedule_update_id = request.GET.get('key')
    event_id = helpers.decode_from_schedule_update_id(schedule_update_id)

    # ===================================================
    # DBデータ取得
    # ===================================================
    # ------------------------
    # イベントレコード
    # ------------------------
    event = Event.objects.get(pk=event_id)

    # ------------------------
    # イベント日時候補レコード
    # ------------------------
    result = EventKouhoNichiji.objects.order_by('id').filter(event=event)
    event_kouho_nichiji_list = [entry for entry in result]

    # ------------------------
    # 当該イベント参加者ｘ参加日時(SankaNichiji)の組み合わせのレコード
    # データ形式：下記形式の辞書（二重）
    # {参加者ID: {"name": 参加者名, "comment": コメント, 参加日時1のイベント候補日時のID: 参加可否（○or△or✕）, 参加日時2のイベント候補日時のID: 参加可否, …}
    # ※Sankashaレコードが取得できない場合（＝誰も参加可否を投入していない場合）、辞書は空となる。
    # ------------------------
    event_sankasha_sankakahi_dict_dict = {}
    try:
        for sankasha in Sankasha.objects.prefetch_related("sankasha_sanka_nichiji_set").filter(event=event):
            sankasha_dict = {}  # 内側の辞書
            sankasha_dict['name'] = sankasha.name
            sankasha_dict['comment'] = sankasha.comment
            for sankanichiji in sankasha.sankasha_sanka_nichiji_set.all():
                sankasha_dict[sankanichiji.event_kouho_nichiji.id] = sankanichiji.sanka_kahi
            event_sankasha_sankakahi_dict_dict[sankasha.id] = sankasha_dict
    except Sankasha.DoesNotExist:
        pass

    # ------------------------
    # イベント日時候補データの1レコードごとの参加日時データ
    # データ形式：下記形式の辞書＆配列
    # {イベント日時候補テーブルID: [参加日時文字列, 参加者1の当時刻の回答レコード, 参加者2の当時刻の回答レコード,…]}
    # ※SankaNichijiレコードが取得できない場合（＝誰も参加可否を投入していない場合）、下記内容となる。
    #   {イベント日時候補テーブルID#1: [参加日時文字列], イベント日時候補テーブルID#2: [参加日時文字列], …}
    # ------------------------
    event_sanka_list_dict = {}
    for event_kouho_nichiji in event_kouho_nichiji_list:
        sanka_nichiji_list_of_a_datetime = SankaNichiji.objects.select_related('event_kouho_nichiji').order_by('id').filter(event_kouho_nichiji=event_kouho_nichiji)
        sanka_nichiji_list_of_a_datetime = [entry for entry in sanka_nichiji_list_of_a_datetime]

app/home/templates/home/event_kouho.html
{% extends "home/base.html" %}
{% load filter static %}

{% block title %}参加可否記入 - 都合くん「この日空いてるっすか。」{% endblock title %}

{% block content %}
<script>
$(function () {
    $('#sanka_kahi_area').on('shown.bs.collapse', function () {
        $("html,body").animate({scrollTop:$('#sanka_kahi_area').offset().top});
    })

    $('a.event_sankashamei_link').click(function(){
        var eventSankashaInfo = $(this).next().val();
        var eventSankashaInfos = eventSankashaInfo.split(',');
        // '参加者1ID,参加者1名前,参加者1のコメント,参加日時1のイベント候補日時のID,参加者1の参加日時1の参加可否,参加日時2のイベント候補日時のID,参加者1の参加日時2の参加可否,…'

        var sankashaId = eventSankashaInfos[0]; // 参加者ID
        var sankashaName = eventSankashaInfos[1]; // 参加者名
        var comment = eventSankashaInfos[2]; // コメント

        $('#sankasha_name').val(sankashaName);
        $('#sankasha_id').val(sankashaId);
        $('#comment').val(comment);

        // 参加可否radioフォームをクリックさせるループ
        for(let i = 3; i < eventSankashaInfos.length; i = i + 2) {
            var kouhoNichiziId = eventSankashaInfos[i];
            var sankaKahi = eventSankashaInfos[i+1];
            $('input[name=event_nichizi_kouho_id_' + kouhoNichiziId +']').val([sankaKahi]);
        }

        // 参加可否回答フォームを開く
        // 開いている状態（class属性にshowがある状態）は遷移する。
        // 開いていない状態（class属性にshowがない状態）はオープンする。
        if($('#sanka_kahi_area').is('[class*="show"]')){
            $("html,body").animate({scrollTop:$('#sanka_kahi_area').offset().top});
        } else {
            $('#sanka_kahi_area').collapse('show');
        }
    });

    if($('#sanka_kahi_area_open').val() === 'true') {
        $('#sanka_kahi_area').collapse('show');
    }
});


</script>
<div class=" row d-flex justify-content-center my-5">
    <div class="col-sm-10">
        <div class="card rounded">
            <div class="card-body">
                <div class="float-right">
                    <a href="{% url 'home:event_edit_prepare' %}?key={{ schedule_update_id }}" class="btn btn-outline-primary">
                        イベント内容を編集する
                    </a>
                </div>
                <h4 class="card-title">{{ event_name }}</h4>
                <p class="card-text">{{ event_memo }}</p>
                <h6 class="card-title">イベント日時候補</h6>
                <div class="table-responsive">
                    <table id="nichizi_kouho_table" class="table table-hover table-bordered mb-5">
                        <thead class="thead-light">
                        <tr>
                            <th>日程</th>
                            <th>○</th>
                            <th>△</th>
                            <th>✕</th>
                            {% for event_sankasha_name, event_sankasha_info in event_sankasha_dict.items %}
                            <th>
                                <div>
                                    <a class="event_sankashamei_link">{{ event_sankasha_name }}</a>
                                    <input type="hidden" value="{{ event_sankasha_info }}">
                                </div>
                            </th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for event_sanka_table_dict in event_sanka_table_dict_list %}
                        <tr>
                            <th>{{ event_sanka_table_dict.nichiji }}</th>
                            <td>{{ event_sanka_table_dict.maru }}</td>
                            <td>{{ event_sanka_table_dict.sankaku }}</td>
                            <td>{{ event_sanka_table_dict.batsu }}</td>
                            {% for event_sankasha_name in event_sankasha_dict.keys %}
                            <td>
                                <div>
                                    {{ event_sanka_table_dict|lookup:event_sankasha_name|to_symbol }}
                                </div>
                            </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        <tr>
                            <th>コメント</th>
                            <td colspan="3"></td>
                            {% for event_sankasha_comment in event_sankasha_comments %}
                            <td style="text-align: center; max-width:100px;">{{ event_sankasha_comment }}</td>
                            {% endfor %}
                        </tr>
                        </tbody>
                    </table>
                </div>

                <p>
                    <a class="btn btn-primary btn-lg btn-block" data-toggle="collapse" href="#sanka_kahi_area"
                       role="button"
                       aria-expanded="false" aria-controls="sanka_kahi_area">
                        参加可否を入力する
                    </a>
                </p>

                <div class="collapse mt-5" id="sanka_kahi_area">
                    <div class="card card-body">
                        <form action="{% url 'home:schedule_fill' %}" method="post">
                            <div class="form-row">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <input type="hidden" name="key" value="{{ schedule_update_id }}">
                                <input type="hidden" id="sankasha_id" name="sankasha_id" value="">
                                <input type="hidden" id="jsoned_params" name="jsoned_params"
                                       value="{{ jsoned_params }}">
                                <input type="hidden" id="sanka_kahi_area_open" name="sanka_kahi_area_open"
                                       value="{{ sanka_kahi_area_open }}">
                            </div>
                            <div class="form-group">
                                <label for="sankasha_name" class="hissu">名前</label>
                                <input type="text" class="form-control" id="sankasha_name" name="name"
                                       aria-describedby="sankashaNameHelp" placeholder="名前・ニックネーム"
                                       value="{{ form.name.value }}">
                                <small id="sankashaNameHelp" class="form-text text-muted">絵文字は入れられません。</small>
                                {{ form.name.errors }}
                            </div>
                            <div class="form-group">
                                <label>イベント日時候補</label>
                                <table id="kaitou_table" class="table table-hover table-bordered">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>日程</th>
                                        <th>○（出席）</th>
                                        <th>△（微妙）</th>
                                        <th>✕（欠席）</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for event_sanka_fill_table_dict in event_sanka_fill_table_dict_list %}
                                    {% comment %}
                                    <!-- ===========================================================================
                                    ----------------------------
                                    event_sanka_fill_table_dict 形式
                                    ----------------------------
                                    nichiji: イベント日時候補文字列（例：X月Y日Z時）
                                    event_nichizi_kouho_id: イベント日時候補テーブルID
                                    selected_value: 選択肢に対応する値（1,2,3）※初期表示は0。
                                    ================================================================================ -->
                                    {% endcomment %}
                                    <tr>
                                        <th>{{ event_sanka_fill_table_dict.nichiji }}</th>
                                        <td>
                                            <input class="form-check-input centered-radio" type="radio"
                                                   name="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   id="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   value="1"
                                                   {% ifequal event_sanka_fill_table_dict.selected_value "1" %}
                                            checked
                                            {% endifequal %}>
                                        </td>
                                        <td>
                                            <input class="form-check-input centered-radio" type="radio"
                                                   name="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   id="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   value="2"
                                                   {% ifequal event_sanka_fill_table_dict.selected_value "2" %}
                                            checked
                                            {% endifequal %}>
                                        </td>
                                        <td>
                                            <input class="form-check-input centered-radio" type="radio"
                                                   name="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   id="event_nichizi_kouho_id_{{ event_sanka_fill_table_dict.event_nichizi_kouho_id }}"
                                                   value="3"
                                                   {% ifequal event_sanka_fill_table_dict.selected_value "3" %}
                                            checked
                                            {% endifequal %}>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="form-group">
                                <label for="comment">コメント</label>
                                <input type="text" class="form-control" id="comment" value="{{ form.comment.value }}"
                                       name="comment" placeholder="コメント・言い訳・感謝、何でもどうぞ。">
                            </div>
                            <div class="form-group d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary px-5">出欠を回答する</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock content %}

app/home/templates/home/event_list.html
{% extends "home/base.html" %}

{% block title %}イベントの一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">イベントの一覧</h4>
<a href="{% url 'home:event_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">イベント名</th>
        <th scope="col">メモ</th>
        <th scope="col">操作</th>
    </tr>
    </thead>
    <tbody>
    {% for event in events %}
    <tr>
        <th scope="row">{{ event.id }}</th>
        <td>{{ event.name }}</td>
        <td>{{ event.memo }}</td>
        <td>
            <a href="{% url 'home:event_mod' event_id=event.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'home:event_del' event_id=event.id %}" class="btn btn-outline-danger btn-sm">削除</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

app/home/templates/home/top.html
{% extends "home/base.html" %}

{% block title %}イベント新規登録 - 都合くん「この日空いてるっすか。」{% endblock title %}

{% block content %}
<div class=" row d-flex justify-content-center my-5">
    <div class="col-sm-10">
        <div class="card rounded">
            <div class="card-body">
                <form action="{% url 'home:event_add' %}" method="post">
                    <div class="form-row">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-6">
                            <div class="form-group">
                                <label for="name" class="hissu">イベント名</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="イベント名"
                                       value="{{ form.name.value }}">
                                {{ form.name.errors }}
                            </div>
                            <div class="form-group">
                                <label for="memo">イベントメモ</label>
                                <textarea class="form-control" id="memo" name="memo"
                                          rows="5">{{ form.memo.value }}</textarea>
                                {{ form.memo.errors }}
                            </div>
                            <div class="form-group">
                                <label for="event_datetime_kouho" class="hissu">イベント日時候補</label>
                                <textarea class="form-control" id="event_datetime_kouho" name="event_datetime_kouho"
                                          rows="5">{{ form.event_datetime_kouho.value }}</textarea>
                                {{ form.event_datetime_kouho.errors }}
                            </div>
                        </div>
                        <div class="form-group col-sm-4">
                            <div class="form-group">
                                <label for="eventDateTimeCalendar">カレンダー</label>
                                <div id="eventDateTimeCalendar"></div>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">新規イベントを登録する</button>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}